all_off:
  name: All Off
  description: Switch off all zones.
  fields:
    device_id:
      name: device_id
      description: The device to send the service call to.
      required: true
      selector:
        device:
          integration: "nuvo_serial"

page_on:
  name: Page On
  description: Activate Paging feature for all zones.
  fields:
    device_id:
      name: device_id
      description: The device to send the service call to.
      required: true
      selector:
        device:
          integration: "nuvo_serial"

page_off:
  name: Page Off
  description: Deactivate Paging feature, restoring all zone to pre-page state.
  fields:
    device_id:
      name: device_id
      description: The device to send the service call to.
      required: true
      selector:
        device:
          integration: "nuvo_serial"

configure_time:
  name: Configure System Time
  description: Set the real time clock in the Grand Concerto.
  fields:
    device_id:
      name: device_id
      description: The device to send the service call to.
      required: true
      selector:
        device:
          integration: "nuvo_serial"
    datetime:
      required: true
      name: datetime
      description: The datetime to send
      example: "'{{ now() | as_local() }}'"
      selector:
        datetime:

snapshot:
  name: Snapshot
  description: Take a snapshot of the current state of a media player zone.
  fields:
    entity_id:
      description: entity_id(s) of media_player zone to snapshot.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
          multiple: true

restore:
  name: Restore
  description: Restore a snapshot of the media player zone.
  fields:
    entity_id:
      description: entity_id(s) of media player zone to restore from snapshot.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
          multiple: true

party_on:
  name: Party On
  description: Make the media player zone the party host.
  fields:
    entity_id:
      description: entity_id of media player zone to make party host.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

party_off:
  name: Party Off
  description: Release the media player zone from being the party host.
  fields:
    entity_id:
      description: entity_id of media player zone to release as party host.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_play_pause_button:
  name: Keypad Play/Pause button
  description: Simulate pressing zone keypad Play/Pause button.
  fields:
    entity_id:
      description: entity_id of media player zone to send the button press from.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_prev_button:
  name: Keypad Prev button
  description: Simulate pressing zone keypad Prev button.
  fields:
    entity_id:
      description: entity_id of media player zone to send the button press from.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"

simulate_next_button:
  name: Keypad Next button
  description: Simulate pressing zone keypad Next button.
  fields:
    entity_id:
      description: entity_id of media player zone to send the button press from.
      example: "media_player.living_room"
      required: true
      selector:
        entity:
          integration: "nuvo_serial"
          domain: "media_player"
